apiVersion: v1
kind: ClusterRole
metadata:
  name: letsencrypt
  labels:
    app: letsencrypt
rules:
- apiGroups:
  - ""
  - "route.openshift.io"
  resources:
  - routes
  - routes/custom-host
  - routes/status
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
